
fault_info:
  weights: 
    mode_inj: 'weight'
    layer: [0]    
  neurons:
    mode_inj: 'neurons'
    layers: [4]
    trials: 5
    size_tail_y: 32 
    size_tail_x: 32
    block_fault_rate_delta: 0.1
    block_fault_rate_steps: 5
    neuron_fault_rate_delta: 0.1
    neuron_fault_rate_steps: 5
    num_threads: 32  
  log_dir: 'FSIMs'
